# Generated by Django 4.2.2 on 2023-06-21 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_service', '0005_alter_restaurantbranch_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ReserveTables',
            fields=[
                ('reservation_id', models.AutoField(db_column='reservation_id', primary_key=True, serialize=False)),
                ('table_id', models.IntegerField(db_column='table_id')),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('branch_id', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, to='user_service.restaurantbranch')),
                ('user_id', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user_app.user')),
            ],
            options={
                'db_table': 'reserved_tables',
            },
        ),
    ]
