# Generated by Django 4.2.2 on 2023-06-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantChain',
            fields=[
                ('chain_name', models.CharField(max_length=256)),
                ('chain_id', models.IntegerField(db_column='chain_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'restaurant_chain',
            },
        ),
    ]
