# Generated by Django 4.2.2 on 2023-07-04 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantBranch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_number', models.IntegerField()),
                ('email', models.CharField()),
                ('number_of_tables', models.IntegerField()),
            ],
            options={
                'db_table': 'restaurant_branch',
            },
        ),
        migrations.CreateModel(
            name='RestaurantChain',
            fields=[
                ('chain_name', models.CharField(max_length=256)),
                ('chain_id', models.IntegerField(db_column='chain_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'restaurant_chain',
            },
        ),
        migrations.CreateModel(
            name='BranchAdress',
            fields=[
                ('branch_id', models.OneToOneField(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_service.restaurantbranch')),
                ('country_name', models.CharField(max_length=512)),
                ('city_name', models.CharField(max_length=512)),
                ('street_name', models.CharField(max_length=512)),
                ('building_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'branch_adress',
            },
        ),
        migrations.CreateModel(
            name='BranchSeatings',
            fields=[
                ('branch_id', models.OneToOneField(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_service.restaurantbranch')),
                ('current_seatings', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='restaurantbranch',
            name='chain_id',
            field=models.ForeignKey(db_column='chain_id', on_delete=django.db.models.deletion.CASCADE, to='user_service.restaurantchain'),
        ),
    ]
