# Generated by Django 4.2.2 on 2023-06-23 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=512)),
                ('city_name', models.CharField(max_length=512)),
                ('street_name', models.CharField(max_length=512)),
                ('building_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'branch_adress',
            },
        ),
        migrations.AlterField(
            model_name='restaurantchain',
            name='chain_id',
            field=models.AutoField(db_column='chain_id', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='RestaurantBranch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_number', models.IntegerField()),
                ('email', models.CharField()),
                ('number_of_tables', models.IntegerField()),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_service.branchaddress')),
                ('chain_id', models.ForeignKey(db_column='chain_id', on_delete=django.db.models.deletion.CASCADE, to='user_service.restaurantchain')),
            ],
            options={
                'db_table': 'restaurant_branch',
            },
        ),
    ]
