# Generated by Django 4.2.2 on 2023-06-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchAdress',
            fields=[
                ('branch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=512)),
                ('city_name', models.CharField(max_length=512)),
                ('street_name', models.CharField(max_length=512)),
                ('building_name', models.CharField(max_length=256)),
            ],
        ),
    ]
