# Generated by Django 4.2.2 on 2023-06-21 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0002_branchadress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchadress',
            name='branch_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_service.restaurantbranch'),
        ),
    ]
