# Generated by Django 4.2.2 on 2023-06-21 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0004_alter_branchadress_branch_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurantbranch',
            table='restaurant_branch',
        ),
        migrations.AlterModelTable(
            name='restaurantchain',
            table='restaurant_chain',
        ),
    ]
