# Generated by Django 4.2.2 on 2023-06-21 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0005_alter_restaurantbranch_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSeatings',
            fields=[
                ('branch_id', models.OneToOneField(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_service.restaurantbranch')),
                ('current_seatings', models.JSONField()),
            ],
        ),
    ]
